In [2]:
import xarray as xr
import geopandas as gpd
import pandas as pd
import numpy as np

In [4]:
my_data = [[1,2,3], [4,5,6], [6,7,8]]
print(my_data)

[[1, 2, 3], [4, 5, 6], [6, 7, 8]]


In [5]:
my_array = np.array(my_data)
print(my_array)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [17]:
my_xr = xr.DataArray(my_array)
print(my_xr)
print(type(my_xr))

<xarray.DataArray (dim_0: 3, dim_1: 3)>
array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])
Dimensions without coordinates: dim_0, dim_1
<class 'xarray.core.dataarray.DataArray'>


In [15]:
my_xr_list = xr.DataArray(my_data)
print(my_xr_list)


<xarray.DataArray (dim_0: 3, dim_1: 3)>
array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])
Dimensions without coordinates: dim_0, dim_1
<class 'xarray.core.dataarray.DataArray'>


In [10]:
my_df = pd.DataFrame(my_data, columns=["1", "2", "3"])
print(my_df)

   1  2  3
0  1  2  3
1  4  5  6
2  6  7  8


In [11]:
my_df = pd.DataFrame(my_array, columns=["1", "2", "3"])
print(my_df)


   1  2  3
0  1  2  3
1  4  5  6
2  6  7  8


In [13]:
my_gpd_df = gpd.GeoDataFrame(my_data, columns=["1", "2", "3"])
print(my_df)

   1  2  3
0  1  2  3
1  4  5  6
2  6  7  8


In [16]:
my_gpd_df = gpd.GeoDataFrame(my_array, columns=["1", "2", "3"])
print(my_df)
print(type(my_df))

   1  2  3
0  1  2  3
1  4  5  6
2  6  7  8
<class 'pandas.core.frame.DataFrame'>
