In [1]:
import pygmt
from pygmt.helpers.testing import load_static_earth_relief
grid = load_static_earth_relief()

In [2]:
result = pygmt.grd2xyz(grid=grid, output_type="numpy")

In [3]:
print(result)

[[-54.5 -10.5 347.5]
 [-53.5 -10.5 331.5]
 [-52.5 -10.5 309. ]
 [-51.5 -10.5 282. ]
 [-50.5 -10.5 190. ]
 [-49.5 -10.5 208. ]
 [-48.5 -10.5 299.5]
 [-47.5 -10.5 348. ]
 [-54.5 -11.5 349. ]
 [-53.5 -11.5 313. ]
 [-52.5 -11.5 325.5]
 [-51.5 -11.5 247. ]
 [-50.5 -11.5 191. ]
 [-49.5 -11.5 225. ]
 [-48.5 -11.5 260. ]
 [-47.5 -11.5 452.5]
 [-54.5 -12.5 345.5]
 [-53.5 -12.5 320. ]
 [-52.5 -12.5 335. ]
 [-51.5 -12.5 292. ]
 [-50.5 -12.5 207.5]
 [-49.5 -12.5 247. ]
 [-48.5 -12.5 325. ]
 [-47.5 -12.5 346.5]
 [-54.5 -13.5 450.5]
 [-53.5 -13.5 395.5]
 [-52.5 -13.5 366. ]
 [-51.5 -13.5 248. ]
 [-50.5 -13.5 250. ]
 [-49.5 -13.5 354.5]
 [-48.5 -13.5 550. ]
 [-47.5 -13.5 797.5]
 [-54.5 -14.5 494.5]
 [-53.5 -14.5 488.5]
 [-52.5 -14.5 357. ]
 [-51.5 -14.5 254.5]
 [-50.5 -14.5 286. ]
 [-49.5 -14.5 484.5]
 [-48.5 -14.5 653.5]
 [-47.5 -14.5 930. ]
 [-54.5 -15.5 601. ]
 [-53.5 -15.5 526.5]
 [-52.5 -15.5 535. ]
 [-51.5 -15.5 299. ]
 [-50.5 -15.5 398.5]
 [-49.5 -15.5 645. ]
 [-48.5 -15.5 797.5]
 [-47.5 -15.5

In [4]:
result.shape

(112, 3)